### PR TITLE
new theme/design for opendata2.0

### PR DESCRIPTION
**Pull request by moppedisco**

### CODE REVIEW

**Review by fabian — APPROVED** [review]
@moppedisco This looks good to me! All changes are in `wp-content/themes/studioyacine` so it shouldn't impact any other sites. If there's any plugins you need you can add them here: 

https://github.com/OpendataCH/opendata.ch/blob/ede8006ec048b91536a93815d8489f0aab4abf89/composer.json#L20-L54

**Comment by loleg** [comment]
@fabian in the Scrutinizer output I see "Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2" - something we should at least keep in mind?

**Review by loleg — CHANGES_REQUESTED** [review]
Looks good, and welcome @moppedisco !

I would appreciate a README in the theme's root with instructions on running `gulp` to start a preview server or to refresh the assets.

**Comment by fabian** [comment]
@loleg Yeah maybe at some point, but there's not a big difference between Composer 1 and 2 AFAIK and we actually don't specify the version of Composer anywhere, so it's up to Scrutinizer to update Composer… 😉

**Comment by moppedisco** [comment]
@loleg readme has been added. 
@fabian All plugins needed you already have listed.

**Review by loleg — APPROVED** [review]

**Pull request merged**
