### PR TITLE
Upgrade to Wordpress 5.2

### PR DESCRIPTION
**Pull request by fabian**
I've started testing this locally, seems to run mostly fine.

Release notes:

- https://wordpress.org/news/2018/12/bebo/
- https://wordpress.org/news/2019/02/betty/
- https://wordpress.org/news/2019/05/jaco/

Issues discovered so far:

- [x] The plugin "vimeo quicktag" is not loaded in the editor. Proposing to simply remove it, can be done with the new video functionality of Wordpress. However some migration for the existing [vimeo] tags would need to be done.

### CODE REVIEW

**Comment by loleg** [comment]
Could vimeo be replaced with a shortcode?

**Comment by fabian** [comment]
@loleg Well there's a `[vimeo]` short code provided by the "vimeo quicktag" plugin now I think.

But it could be replaced by the native `[video]` short code, we just need to find a good way to do a  search and replace in all old articles.

**Comment by loleg** [comment]
@fabian the easiest S&R would be direct in the database, no?

**Comment by fabian** [comment]
The vimeo quicktag plugin was actually already broken on the current website. I've done a search on the database and only 2 pages were using the shortcode.

I've gone ahead now and manually replaced those two shortcodes and remove the Vimeo quicktag plugin.

**Comment by fabian** [comment]
Scheduled for merge and deploy on 20.07.2019.

**Pull request merged**
